FROM python:3.10-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

ENV PYTHONUNBUFFERED 1

ARG PORT
ENV PORT ${PORT:-8000}

ARG PROCESSES_NUM
ENV PROCESSES_NUM ${PROCESSES_NUM:-4}

ARG WEB_CONCURRENCY
ENV WEB_CONCURRENCY ${WEB_CONCURRENCY:-4}

WORKDIR /app

# install requirements
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

COPY . /app

CMD ["/docker-entrypoint.sh"]
